### ISSUE TITLE
Post image is black, after swapping images

### ISSUE THREAD

**Issue by tomaytotomato** [getgrav/grav-theme-mediator#16]
I have been testing the mediator theme and come across a strange issue.

When trying to create a new blog post or edit an existing one. I cannot seem to change to the post image without breaking it (i.e. the top of the blog post goes black)

http://brucetaylor.xyz/blog/welcome-to-grav

http://brucetaylor.xyz/blog/sample-post

As in the case here, I added a new image to replace to the old one. Then after saving the post it goes black.

Cleared cache and also tried adding it to the markdown post but that didn't work either.

Is there some hardcoded mapping? All the examples don't have any image link in the markdown but they seem to work until I change the image.

When you look at the markup, there is no image specified in the background-image CSS attribute. Is there some PHP or Javascript that is breaking?

**Comment by flaviocopes** [comment]
Is this a theme-specific issue, or you are getting this problem also with the Antimatter theme for example?

**Comment by tomaytotomato** [comment]
I downloaded the mediator theme skeleton that came with these sample posts. Why the post title image breaks when changing photo.

--Update--

So looking at the raw markdown files, there is a property for 

`image: swim.jpg`

However this is not displayed on the Grav Admin GUI when editing a page unless you goto "Expert" mode.

Please update the docs for this.

**Comment by flaviocopes** [comment]
Merged https://github.com/getgrav/grav-skeleton-mediator-site/pull/3, thanks
