### ISSUE TITLE
Missing metadata file

### ISSUE THREAD

**Issue by gizmecano** [getgrav/grav-theme-mediator#21]
The file `metadata.html.twig` is supposed to be included in `base.html.twig` but seems to not exist in the `partials` folder.

https://github.com/getgrav/grav-theme-mediator/blob/1c31de5de7bd321b6d571efd24ec9b70949de6d6/templates/partials/base.html.twig#L11

**Comment by ricardo118** [comment]
@gizmecano the file exists in `system/templates/partials`

**Comment by gizmecano** [comment]
Well, thank you.

That means that the `metadata.html.twig` file used is already in `system/templates/partials` and does not need to be added in `user/themes/mediator/templates/partials/` as I thought.
